### PR TITLE
 [ExportedProgram] Add mutable attribute to buffer

### PR DESCRIPTION
**Pull request by chrsmcgrr**
Fixes iree-org/iree-turbine#85

PR based on the work of @maxbartel 

Requires changes in torch-mlir: [llvm/torch-mlir/#3688](https://github.com/llvm/torch-mlir/pull/3688)

Adds the mutable modifier to a global buffer and lifts said buffer to a global if there is a store-producer node associated with it.

### CODE REVIEW

**Comment by chrsmcgrr** [comment]
Requires newer version of IREE containing the torch-mlir change: https://github.com/iree-org/iree-turbine/pull/142

**Comment by chrsmcgrr** [comment]
> Requires newer version of IREE containing the torch-mlir change: #151

Actually this PR did not have the IREE changes that were required. A newer release is needed.

**Comment by maxbartel** [comment]
Could you rebase, please? The tests should now pass

**Comment by maxbartel** [comment]
@stellaraccident This seems to work now with the newest IREE bump. Can we get a review from you please?

**Review by stellaraccident — APPROVED** [review]
Amazing -- I don't know if you truly know how many things had to come together to make that work. I've been slowly making progress on that functionality for the past year because it seemed very useful to get mapped right, but I didn't know we were so close to having it fully working.

**Pull request merged**
