### PR TITLE
Add ops.iree.transfer_to_logical_device() custom op.

### PR DESCRIPTION
**Pull request by stellaraccident**
This exposes IREE's multi-device capabilities to PyTorch programs, allowing them to transfer parts of the computation to other devices. This will be used as part of the sharding work in sharktank to do auto placement of sharded tensors (i.e. across GPU devices, etc). But it is also available for heterogenous/ad-hoc offload to other devices (GPU slices, CPU slices, NPU, etc).

Since this is the first op we have that has different eager vs graph mode semantics, add a new CustomOp.eager_execute() hook which allows the eager execution semantics to be specified separately from graph compilation. Since these local device transfers are only meaningful within an IREE program, they are no-ops during eager execution.

(requires a WIP branch on IREE)

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by sogartar** [comment]
I rebased the PR, I have more PRs that depend on this.

**Comment by sogartar** [comment]
The CI is failing due to not having a recent enough python package if IREE, that includes the [multi-device work](https://github.com/iree-org/iree/pull/17987).

The release package of IREE is failing due to https://github.com/iree-org/iree/actions/runs/10294193487/job/28492076494

**Comment by sogartar** [comment]
Actually we are not using nightly packages for the CI, but the ones published to `pypi.org`. I guess this is intentional? Then we need to update the IREE pypi packages.

**Comment by stellaraccident** [comment]
Not intentional to be pinned like that. Feel free to pin to an appropriate nightly.

**Pull request merged**
